# Generated by Django 2.2.28 on 2023-03-07 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=30)),
                ('storeDescription', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tagName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profilePicture', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=128)),
                ('phoneNo', models.CharField(max_length=11)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rango.UserAccount', unique=True)),
                ('sellerName', models.CharField(max_length=30)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=30)),
                ('isDigital', models.BooleanField()),
                ('itemDescription', models.CharField(max_length=128)),
                ('itemImage', models.ImageField(upload_to='')),
                ('condition', models.CharField(max_length=10)),
                ('listedTime', models.DateTimeField()),
                ('sellTime', models.DateTimeField()),
                ('buyNowPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.UserAccount')),
                ('sellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Sellers')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidTime', models.DateTimeField()),
                ('bidPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Items')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.UserAccount')),
            ],
        ),
    ]
