# Generated by Django 2.2.28 on 2023-03-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('storeID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('storeName', models.CharField(max_length=30)),
                ('storeDescription', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('profilePicture', models.ImageField(blank=True, upload_to='')),
                ('description', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('phoneNo', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sellerName', models.CharField(max_length=30)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rango.Users')),
            ],
            options={
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tagID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('tagName', models.CharField(max_length=30)),
                ('shopname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Stores')),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('itemName', models.CharField(max_length=30)),
                ('isDigital', models.BooleanField()),
                ('itemDescription', models.CharField(max_length=128)),
                ('itemImage', models.ImageField(blank=True, upload_to='')),
                ('condition', models.CharField(max_length=10)),
                ('listedTime', models.DateTimeField()),
                ('sellTime', models.DateTimeField()),
                ('buyNowPrice', models.FloatField(default=0.0, max_length=100)),
                ('storename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Stores')),
                ('tags', models.ManyToManyField(to='rango.Tags')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Users')),
                ('sellerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Seller')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('bidID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('bidTime', models.DateTimeField()),
                ('bidPrice', models.FloatField(default=0.0, max_length=100)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Items')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Users')),
            ],
            options={
                'verbose_name_plural': 'Bids',
            },
        ),
    ]
