# Generated by Django 2.2.28 on 2023-03-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20230307_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tagID',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
