# Generated by Django 2.2.28 on 2023-03-20 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('storeID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('storeName', models.CharField(max_length=30)),
                ('storeDescription', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('profilePicture', models.ImageField(blank=True, upload_to='user_profile_photos/')),
                ('description', models.CharField(max_length=128)),
                ('phoneNo', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('sellerID', models.AutoField(primary_key=True, serialize=False)),
                ('sellerName', models.CharField(max_length=30)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WhiteMarket.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('itemName', models.CharField(max_length=30, unique=True)),
                ('sellerName', models.CharField(max_length=30)),
                ('isDigital', models.BooleanField()),
                ('itemDescription', models.CharField(max_length=128)),
                ('itemImage', models.ImageField(upload_to='item_photos/')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=10)),
                ('listedTime', models.DateTimeField(auto_now_add=True)),
                ('sellTime', models.DateTimeField(blank=True, null=True)),
                ('buyNowPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(unique=True)),
                ('sellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemSellerID', to='WhiteMarket.Sellers')),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WhiteMarket.Stores')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('bidID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bidTime', models.DateTimeField()),
                ('bidPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('complete', models.BooleanField(default=False)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WhiteMarket.Items')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WhiteMarket.UserProfile')),
            ],
        ),
    ]
