# Generated by Django 2.2.28 on 2023-03-15 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WhiteMarket', '0002_auto_20230311_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('bidID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('bidTime', models.DateTimeField()),
                ('bidPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('itemName', models.CharField(max_length=30)),
                ('isDigital', models.BooleanField()),
                ('itemDescription', models.CharField(max_length=128)),
                ('itemImage', models.ImageField(upload_to='')),
                ('condition', models.CharField(max_length=10)),
                ('listedTime', models.DateTimeField()),
                ('sellTime', models.DateTimeField()),
                ('buyNowPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('storeID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('storeName', models.CharField(max_length=30)),
                ('storeDescription', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tagName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('profilePicture', models.ImageField(blank=True, upload_to='profile_images')),
                ('description', models.CharField(max_length=128)),
                ('phoneNo', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WhiteMarket.Users')),
                ('sellerName', models.CharField(max_length=30)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='items',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemUserID', to='WhiteMarket.Users'),
        ),
        migrations.AddField(
            model_name='items',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='WhiteMarket.Users'),
        ),
        migrations.AddField(
            model_name='bids',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WhiteMarket.Items'),
        ),
        migrations.AddField(
            model_name='bids',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WhiteMarket.Users'),
        ),
        migrations.AddField(
            model_name='items',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerID', to='WhiteMarket.Sellers'),
        ),
        migrations.AddField(
            model_name='items',
            name='sellerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemSellerName', to='WhiteMarket.Sellers'),
        ),
    ]
