# Generated by Django 2.2.28 on 2023-03-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteMarket', '0002_auto_20230321_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=11),
        ),
    ]
