# Generated by Django 2.2.28 on 2023-03-18 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WhiteMarket', '0003_auto_20230315_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('profilePicture', models.ImageField(blank=True, upload_to='profile_images')),
                ('description', models.CharField(max_length=128)),
                ('phoneNo', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.RemoveField(
            model_name='items',
            name='userID',
        ),
        migrations.AlterField(
            model_name='bids',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WhiteMarket.UserProfile'),
        ),
        migrations.AlterField(
            model_name='items',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=10),
        ),
        migrations.AlterField(
            model_name='items',
            name='listedTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='sellTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='WhiteMarket.UserProfile'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WhiteMarket.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
