# Generated by Django 2.2.28 on 2023-03-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteMarket', '0004_auto_20230318_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='sellerID',
            field=models.AutoField(default=37, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemSellerID', to='WhiteMarket.Sellers'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WhiteMarket.UserProfile'),
        ),
    ]
