# Generated by Django 2.2.28 on 2023-03-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteMarket', '0005_auto_20230319_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='username',
        ),
    ]
