# Generated by Django 2.2.28 on 2023-03-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteMarket', '0006_remove_items_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='sellerName',
        ),
    ]
