# Generated by Django 2.2.28 on 2023-03-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteMarket', '0007_remove_items_sellername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemName',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
