# Generated by Django 2.2.28 on 2023-03-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteMarket', '0008_auto_20230319_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemImage',
            field=models.ImageField(upload_to='item_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to='user_profile_photos/'),
        ),
    ]
