# Generated by Django 2.2.28 on 2023-03-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteMarket', '0009_auto_20230319_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
