# Generated by Django 2.2.28 on 2023-03-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteMarket', '0010_auto_20230319_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='sellerName',
            field=models.CharField(default='genericSeller', max_length=30),
            preserve_default=False,
        ),
    ]
