# Generated by Django 2.2.28 on 2023-03-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteMarket', '0012_items_storeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='storeID',
        ),
    ]
