# Generated by Django 2.2.28 on 2023-03-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteMarket', '0013_remove_items_storeid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='items',
            name='storeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WhiteMarket.Stores'),
            preserve_default=False,
        ),
    ]
