# Generated by Django 2.2.28 on 2023-03-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteMarket', '0014_auto_20230319_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
