# Generated by Django 2.2.28 on 2023-03-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteMarket', '0015_bids_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
